version: "3.8"

services:

  auth_service:
    image: auth_service
    container_name: auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    restart: always
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network
    volumes:
      - mongo_store:/data/db

  auth_db:
    image: mongo:4.4.6
    container_name: auth_db
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  mongo_store:
